In [1]:
import numpy as np

In [3]:
prim_array = np.array([[0,1,2,3],[4,5,6,7]])

In [8]:
prim_array

array([[ 0,  1,  2,  3],
       [ 4, 21,  6,  7]])

In [5]:
prim_array.shape

(2, 4)

In [6]:
prim_array[1,0]

np.int64(4)

In [9]:
prim_array[1,1] = 21
prim_array[0,0] = 99

In [10]:
prim_array

array([[99,  1,  2,  3],
       [ 4, 21,  6,  7]])

In [11]:
# Columna 1
prim_array[:,0]

array([99,  4])